version: '2'
services:
    microservice-app:
        image: microservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://microservice-mysql:3306/microservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    microservice-mysql:
        extends:
            file: mysql.yml
            service: microservice-mysql
